const respone = {
  kind: "customsearch#search",
  url: {
    type: "application/json",
    template:
      "https://www.googleapis.com/customsearch/v1?q={searchTerms}&num={count?}&start={startIndex?}&lr={language?}&safe={safe?}&cx={cx?}&sort={sort?}&filter={filter?}&gl={gl?}&cr={cr?}&googlehost={googleHost?}&c2coff={disableCnTwTranslation?}&hq={hq?}&hl={hl?}&siteSearch={siteSearch?}&siteSearchFilter={siteSearchFilter?}&exactTerms={exactTerms?}&excludeTerms={excludeTerms?}&linkSite={linkSite?}&orTerms={orTerms?}&relatedSite={relatedSite?}&dateRestrict={dateRestrict?}&lowRange={lowRange?}&highRange={highRange?}&searchType={searchType}&fileType={fileType?}&rights={rights?}&imgSize={imgSize?}&imgType={imgType?}&imgColorType={imgColorType?}&imgDominantColor={imgDominantColor?}&alt=json",
  },
  queries: {
    request: [
      {
        title: "Google Custom Search - tailwind css",
        totalResults: "62000000",
        searchTerms: "tailwind css",
        count: 10,
        startIndex: 1,
        inputEncoding: "utf8",
        outputEncoding: "utf8",
        safe: "off",
        cx: "7741f7c931b0f1e98",
        searchType: "image",
      },
    ],
    nextPage: [
      {
        title: "Google Custom Search - tailwind css",
        totalResults: "62000000",
        searchTerms: "tailwind css",
        count: 10,
        startIndex: 11,
        inputEncoding: "utf8",
        outputEncoding: "utf8",
        safe: "off",
        cx: "7741f7c931b0f1e98",
        searchType: "image",
      },
    ],
  },
  context: {
    title: "go-v3",
  },
  searchInformation: {
    searchTime: 0.506317,
    formattedSearchTime: "0.51",
    totalResults: "62000000",
    formattedTotalResults: "62,000,000",
  },
  items: [
    {
      kind: "customsearch#result",
      title: "Designing with Tailwind CSS",
      htmlTitle: "Designing with <b>Tailwind CSS</b>",
      link: "https://v1.tailwindcss.com/_next/static/media/workcation-screenshot.e15fad2353857da51319620da615ff93.jpg",
      displayLink: "v1.tailwindcss.com",
      snippet: "Designing with Tailwind CSS",
      htmlSnippet: "Designing with <b>Tailwind CSS</b>",
      mime: "image/jpeg",
      fileFormat: "image/jpeg",
      image: {
        contextLink: "https://v1.tailwindcss.com/course",
        height: 1059,
        width: 1473,
        byteSize: 159308,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_G2HsPrg1S6oU3TvAfubMUxncbGChfjrSGmuIlvbqu2CdyuQHoejukQ&s",
        thumbnailHeight: 108,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "Tailwind CSS IntelliSense | Laravel News",
      htmlTitle: "<b>Tailwind CSS</b> IntelliSense | Laravel News",
      link: "https://laravelnews.s3.amazonaws.com/images/tailwind-intellisense.jpg",
      displayLink: "laravel-news.com",
      snippet: "Tailwind CSS IntelliSense | Laravel News",
      htmlSnippet: "<b>Tailwind CSS</b> IntelliSense | Laravel News",
      mime: "image/jpeg",
      fileFormat: "image/jpeg",
      image: {
        contextLink: "https://laravel-news.com/tailwind-css-intellisense",
        height: 1100,
        width: 2200,
        byteSize: 282961,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHc3xvxL6WNNmQqp83tIB0anI-ncCTq3PLz882s5QWEQCETdab0NslmV0&s",
        thumbnailHeight: 75,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "Utility-First Fundamentals - Tailwind CSS",
      htmlTitle: "Utility-First Fundamentals - <b>Tailwind CSS</b>",
      link: "https://tailwindcss.com/_next/static/media/social-square.eab77323.jpg",
      displayLink: "tailwindcss.com",
      snippet: "Utility-First Fundamentals - Tailwind CSS",
      htmlSnippet: "Utility-First Fundamentals - <b>Tailwind CSS</b>",
      mime: "image/jpeg",
      fileFormat: "image/jpeg",
      image: {
        contextLink: "https://tailwindcss.com/docs/utility-first",
        height: 1200,
        width: 1200,
        byteSize: 21851,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiugYWCGi_axNAcVTKoDn7ncVOrHYaSldLUqw-MfcUbiz43mXk3M60W65h&s",
        thumbnailHeight: 150,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "The first alpha of Tailwind CSS v3 is now released | Laravel News",
      htmlTitle: "The first alpha of <b>Tailwind CSS</b> v3 is now released | Laravel News",
      link: "https://laravelnews.imgix.net/images/tailwindcss-1633184775.jpg?ixlib=php-3.3.1",
      displayLink: "laravel-news.com",
      snippet: "The first alpha of Tailwind CSS v3 is now released | Laravel News",
      htmlSnippet: "The first alpha of <b>Tailwind CSS</b> v3 is now released | Laravel News",
      mime: "image/jpeg",
      fileFormat: "image/jpeg",
      image: {
        contextLink: "https://laravel-news.com/tailwind-css-v3-alpha",
        height: 1100,
        width: 2200,
        byteSize: 65562,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsRmdk4jTMcMSzmbmoF20EoqSmX5CZzFE23Uu3SRZWLS6V7C9S11FWvS4&s",
        thumbnailHeight: 75,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "10+ Free Tailwind CSS Templates & Resources for 2021",
      htmlTitle: "10+ Free <b>Tailwind CSS</b> Templates &amp; Resources for 2021",
      link: "https://www.creative-tim.com/blog/content/images/size/w960/wordpress/2021/02/blog-2.jpg",
      displayLink: "www.creative-tim.com",
      snippet: "10+ Free Tailwind CSS Templates & Resources for 2021",
      htmlSnippet: "10+ Free <b>Tailwind CSS</b> Templates &amp; Resources for 2021",
      mime: "image/jpeg",
      fileFormat: "image/jpeg",
      image: {
        contextLink:
          "https://www.creative-tim.com/blog/web-development/free-tailwind-css-templates-resources/",
        height: 410,
        width: 730,
        byteSize: 28893,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCQtA0gjpbsXdbg6HdEfoZe8VHNwbbA5FtLUpDe92_aHc0XjDsKbFG3Is&s",
        thumbnailHeight: 79,
        thumbnailWidth: 141,
      },
    },
    {
      kind: "customsearch#result",
      title: "State of CSS 2020 Survey Results: Tailwind CSS Wins Most Adopted ...",
      htmlTitle:
        "State of <b>CSS</b> 2020 Survey Results: <b>Tailwind CSS</b> Wins Most Adopted ...",
      link: "https://149611589.v2.pressablecdn.com/wp-content/uploads/2020/12/state-of-css-2020.png",
      displayLink: "wptavern.com",
      snippet: "State of CSS 2020 Survey Results: Tailwind CSS Wins Most Adopted ...",
      htmlSnippet:
        "State of <b>CSS</b> 2020 Survey Results: <b>Tailwind CSS</b> Wins Most Adopted ...",
      mime: "image/png",
      fileFormat: "image/png",
      image: {
        contextLink:
          "https://wptavern.com/state-of-css-2020-survey-results-tailwind-css-wins-most-adopted-technology-utility-first-css-on-the-rise",
        height: 1210,
        width: 2100,
        byteSize: 336654,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7J4T3nFo1ik-axOhMsUXO3h-t9yZNAP09VeI06nv1l2QMmBCz4zvU7eo&s",
        thumbnailHeight: 86,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "Tailwind CSS Starter Kit | Drupal.org",
      htmlTitle: "<b>Tailwind CSS</b> Starter Kit | Drupal.org",
      link: "https://www.drupal.org/files/project-images/screenshot_361.png",
      displayLink: "www.drupal.org",
      snippet: "Tailwind CSS Starter Kit | Drupal.org",
      htmlSnippet: "<b>Tailwind CSS</b> Starter Kit | Drupal.org",
      mime: "image/png",
      fileFormat: "image/png",
      image: {
        contextLink: "https://www.drupal.org/project/tailwindcss",
        height: 400,
        width: 400,
        byteSize: 7158,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQniGOFIc0T_Pxp6gVSF0zDGIbdKfIUgHYNI0CAlwzuQr76oorrLhnj5A&s",
        thumbnailHeight: 124,
        thumbnailWidth: 124,
      },
    },
    {
      kind: "customsearch#result",
      title: "Tailwind CSS | WebStorm",
      htmlTitle: "<b>Tailwind CSS</b> | WebStorm",
      link: "https://resources.jetbrains.com/help/img/idea/2022.2/ws_tailwind_css_preview_completion_dark.png",
      displayLink: "www.jetbrains.com",
      snippet: "Tailwind CSS | WebStorm",
      htmlSnippet: "<b>Tailwind CSS</b> | WebStorm",
      mime: "image/png",
      fileFormat: "image/png",
      image: {
        contextLink: "https://www.jetbrains.com/help/webstorm/tailwind-css.html",
        height: 656,
        width: 1412,
        byteSize: 76511,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0I45FN_WbjiV07lao64s-qsFTtfp7cRUmxDpjdFHXF9x8rL3YyF7Vxg&s",
        thumbnailHeight: 70,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "Material Tailwind Kit React: Free Tailwind CSS & Material Design ...",
      htmlTitle:
        "Material <b>Tailwind</b> Kit React: Free <b>Tailwind CSS</b> &amp; Material Design ...",
      link: "https://s3.amazonaws.com/creativetim_bucket/products/486/original/opt_mtr_thumbnail.jpg?1623313854",
      displayLink: "www.creative-tim.com",
      snippet: "Material Tailwind Kit React: Free Tailwind CSS & Material Design ...",
      htmlSnippet:
        "Material <b>Tailwind</b> Kit React: Free <b>Tailwind CSS</b> &amp; Material Design ...",
      mime: "image/jpeg",
      fileFormat: "image/jpeg",
      image: {
        contextLink: "https://www.creative-tim.com/product/material-tailwind-kit-react",
        height: 600,
        width: 800,
        byteSize: 90436,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRX-wHY-cczVV_RC0ru4LDgYnmVdwBFYOa8qhlWYV0kIhWdjQ44ectkwdM&s",
        thumbnailHeight: 107,
        thumbnailWidth: 143,
      },
    },
    {
      kind: "customsearch#result",
      title: "File:Tailwind CSS Logo.svg - Wikimedia Commons",
      htmlTitle: "File:<b>Tailwind CSS</b> Logo.svg - Wikimedia Commons",
      link: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Tailwind_CSS_Logo.svg/1200px-Tailwind_CSS_Logo.svg.png",
      displayLink: "commons.wikimedia.org",
      snippet: "File:Tailwind CSS Logo.svg - Wikimedia Commons",
      htmlSnippet: "File:<b>Tailwind CSS</b> Logo.svg - Wikimedia Commons",
      mime: "image/png",
      fileFormat: "image/png",
      image: {
        contextLink: "https://commons.wikimedia.org/wiki/File:Tailwind_CSS_Logo.svg",
        height: 1200,
        width: 1200,
        byteSize: 34754,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8fAjVvARrp_F2ObzyIky6qby0diApfGlENNuf8PFM8ZE2gI5SYyfsRJ4&s",
        thumbnailHeight: 150,
        thumbnailWidth: 150,
      },
    },
  ],
};
export default respone;
